name: Deploy into staging

on:
  workflow_dispatch:
    secrets:
      PAT:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call_reusable_workflow:
    uses: eammosov/cicd_actions/.github/workflows/merge_branches.yml@main
    with:
      origin_branch: "main"
      merge_branch: "staging"
    secrets:
      token: "${{ secrets.PAT }}"
