name: Deploy into production

on:
  workflow_dispatch:
    secrets:
      PAT:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ORIGIN_BRANCH: 'staging'
  MERGE_BRANCH: 'production'

jobs:
  call_reusable_workflow:
    uses: eammosov/cicd_actions/.github/workflows/merge_branches.yml@main
    with:
      origin_branch: "staging"
      merge_branch: "production"
    secrets:
      token: "${{ secrets.PAT }}"
