name: Deploy into production

on:
  workflow_dispatch:
    branches:
      - staging
    inputs:
      origin_branch:
        required: true
        type: string
        default: 'staging'
      merge_branch:
        required: true
        type: string
        default: 'production'
    secrets:
      PAT:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call_reusable_workflow:
    uses: eammosov/cicd_actions/.github/workflows/merge_branches.yml@main
    with:
      origin_branch: ${{ inputs.origin_branch }}
      merge_branch: ${{ inputs.merge_branch }}
    secrets:
      token: "${{ secrets.PAT }}"
