# File: .github/workflows/caller-workflow.yml
name: Caller Workflow

on:
  workflow_dispatch:


jobs:
  call_reusable_workflow:
    uses: eammosov/cicd_actions/.github/workflows/pr-merge.yml@main
    secrets:
      token: "${{ secrets.PAT }}"
