

# File: .github/workflows/caller-workflow.yml
name: Caller Workflow

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
  workflow_dispatch:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  call_reusable_workflow:
    uses: eammosov/cicd_actions/.github/workflows/pr-merge.yml@main
    with:
      username: ${{ github.actor }}
      token: ${{ secrets.GITHUB_TOKEN }}

  local_job:
    runs-on: ubuntu-latest
    needs: call_reusable_workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run local task
        run: |
          echo "Выполняю локальную задачу после вызова внешнего рабочего процесса"
