

# File: .github/workflows/caller-workflow.yml
name: Caller Workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  call_reusable_workflow:
    uses: eammosov/cicd_actions/.github/workflows/pr-merge.yml@main
    with:
      username: ${{ github.actor }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    #    env:
    #      token: ${{ secrets.GITHUB_TOKEN }}
