# File: .github/workflows/caller-workflow.yml
name: Caller Workflow

on:
  workflow_dispatch:
    secrets:
      PAT:
        required: true

jobs:
  call_reusable_workflow:
    uses: eammosov/cicd_actions/.github/workflows/pr-merge.yml@main
    with:
      token: ${{ secrets.PAT }}
