# File: .github/workflows/caller-workflow.yml
name: Production

on:
  workflow_dispatch:
    branches:
      - staging
    inputs:
      origin_branch:
        required: true
        type: string
        default: 'staging'
      merge_branch:
        required: true
        type: string
        default: 'production'
    secrets:
      PAT:
        required: true

jobs:
  call_reusable_workflow:
    uses: eammosov/cicd_actions/.github/workflows/pr-production.yml@main
    with:
      merge_branch: ${{ inputs.merge_branch }}
    secrets:
      token: "${{ secrets.PAT }}"
