# File: .github/workflows/caller-workflow.yml
name: Production

on:
  workflow_dispatch:
    secrets:
      PAT:
        required: true

jobs:
  call_reusable_workflow:
    uses: eammosov/cicd_actions/.github/workflows/pr-production.yml@main
    secrets:
      token: "${{ secrets.PAT }}"
