# File: .github/workflows/caller-workflow.yml
name: Staging

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      origin_branch:
        required: true
        type: string
        default: 'main'
      merge_branch:
        required: true
        type: string
        default: 'staging'
    secrets:
      PAT:
        required: true

jobs:
  call_reusable_workflow:
    uses: eammosov/cicd_actions/.github/workflows/pr-staging.yml@main
    with:
      origin_branch: ${{ inputs.origin_branch }}
      merge_branch: ${{ inputs.merge_branch }}
    secrets:
      token: "${{ secrets.PAT }}"
